# 📊 Calculative Foundation Project
## Linear Algebra for Student Performance Dataset

**Duration:** 6 Hours  
**Type:** Theory + Practical  

This notebook demonstrates Linear Algebra concepts such as vectors, matrices, decompositions, and dimensionality reduction applied to a student performance dataset.

## 📦 Import Libraries

In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import norm, eig, det, inv
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

## 📁 Load Dataset
Replace this with your dataset file.

In [2]:
# Example dataset
data = {
    'Math':[78,85,96,65,88],
    'Physics':[82,79,94,70,90],
    'Chemistry':[75,88,92,60,85]
}

df = pd.DataFrame(data)
df

,Math,Physics,Chemistry
0,78,82,75
1,85,79,88
2,96,94,92
3,65,70,60
4,88,90,85


# 🔹 Part A: Vector & Matrix Fundamentals

In [3]:
# Represent each student as a vector
vectors = df.values
vectors

array([[78, 82, 75],
       [85, 79, 88],
       [96, 94, 92],
       [65, 70, 60],
       [88, 90, 85]])

In [4]:
# Norm-1 and Norm-2
norm1 = np.linalg.norm(vectors, ord=1)
norm2 = np.linalg.norm(vectors)

norm1, norm2

(np.float64(415.0), np.float64(319.3007986209868))

# 🔹 Part B: Matrix Operations

In [5]:
matrix = df.values

transpose = matrix.T
determinant = det(matrix.T @ matrix)

transpose, determinant

(array([[78, 85, 96, 65, 88],
        [82, 79, 94, 70, 90],
        [75, 88, 92, 60, 85]]),
 np.float64(35809237.99997274))

# 🔹 Part C: Linear Transformations

In this dataset:

- Each subject represents a **dimension**.
- 2 subjects → 2D plane
- 3 subjects → 3D space
- Many subjects → **Higher dimensional space (hyperplane)**

# 🔹 Part D: Eigenvalues & Decomposition

In [6]:
cov_matrix = np.cov(matrix, rowvar=False)
eigenvalues, eigenvectors = eig(cov_matrix)

eigenvalues, eigenvectors

(array([369.3405577 ,   0.53892533,  19.92051697]),
 array([[ 0.60664396,  0.79380968, -0.04300351],
        [ 0.4540378 , -0.39037228, -0.80091146],
        [ 0.65255864, -0.46634288,  0.59723658]]))

# 🔹 Part E: PCA (Dimensionality Reduction)

In [10]:
pca = PCA(n_components=2)
pca_result = pca.fit_transform(matrix)

pca_result

array([[ -6.38606444,   1.99605602],
       [  4.98159225,  -7.86972937],
       [ 21.07547737,   2.22803477],
       [-29.50926915,   0.78462164],
       [  9.83826398,   2.86101694]])

# 🔹 LDA Classification

In [8]:
# Create simple labels
labels = ['Above','Above','Above','Below','Above']

lda = LDA(n_components=1)
lda_result = lda.fit_transform(matrix, labels)

lda_result

array([[-0.55330694],
       [-1.79310023],
       [-1.31929388],
       [ 6.606992  ],
       [-2.94129096]])

# ✅ Conclusion

This project demonstrates:

- Vector representation of real-world data
- Matrix operations
- Eigenvalues and eigenvectors
- PCA for dimensionality reduction
- LDA for classification

These techniques are fundamental in **Machine Learning and Data Science.**